name: distPyLib
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - cmake
  - ninja
  - pybind11
  - openmpi
  - mpi4py
  - pytest
  - pip
  - clang
  - gtest
  - pip:
    - pybind11[global]
    - pytest