"""Type stub for _mpi_core module."""

from typing import List

class MPIWrapper:
    def __init__(self) -> None: ...
    def initialize(self) -> None: ...
    def parallel_compute(self, data: List[float]) -> List[float]: ...
    def get_rank(self) -> int: ...
    def get_size(self) -> int: ...
    def is_initialized(self) -> bool: ...
    def spawn_processes(self, num_processes: int) -> None: ...
    