"""Type stub for _parallel_sum module."""

from typing import List

class ParaSum:
    def __init__(self) -> None: ...
    def initialize(self) -> None: ...
    def parallel_sum(self, data: List[float]) -> List[float]: ...
    def get_rank(self) -> int: ...
    def get_size(self) -> int: ...
    def is_initialized(self) -> bool: ...
    